let peliculas = {
    'pelicula1': {
        'titulo': 'The Post',
        'anio': '2017',
        'duracion': '116 min',
        'direccion': 'Steven Spielberg',
        'votos': 0,
        'sinopsis': 'En junio de 1971, los principales periódicos de EE.UU., entre los que se encontraban The New York Times y The Washington Post, tomaron una valiente posición en favor de la libertad de expresión, informando sobre los documentos del Pentágono y el encubrimiento masivo de secretos por parte del gobierno, que había durado cuatro décadas y cuatro presidencias estadounidenses. En ese momento, Katherine Graham (Meryl Streep), primera mujer editora del Post, y el director Ben Bradlee (Tom Hanks) intentaba relanzar un periódico en decadencia. Juntos decidieron tomar la audaz decisión de apoyar al The New York Times y luchar contra el intento de la Administración Nixon de restringir la primera enmienda... Historia basada en los documentos del Post que recogían información clasificada sobre la Guerra de Vietnam. Su publicación generó un enorme debate sobre la libertad de expresión y acabó en una dura batalla legal ante el Tribunal Supremo.',
        'image': 'images/thePost.jpg',
    },
    'pelicula2': {
        'titulo': 'Mazinger Z',
        'anio': '2017',
        'duracion': '95 min',
        'direccion': 'Junji Shimizu',
        'votos': 0,
        'sinopsis': 'Cuando el malvado Doctor Hell ataca la Tierra, el poderoso robot gigante Mazinger Z se decide a detenerlo.',
        'image': 'images/mazingerZ.jpg',
    },
    'pelicula3': {
        'titulo': '120 battements par minute',
        'anio': '2017',
        'duracion': '143 min',
        'direccion': 'Robin Campillo',
        'votos': 0,
        'sinopsis': 'París, principios de los años 90. Un grupo de jóvenes activistas intenta generar conciencia sobre el SIDA. Un nuevo miembro del grupo, Nathan, se quedará sorprendido ante la radicalidad y energía de Sean, que gasta su último aliento en la lucha.',
        'image': 'images/120battements.jpg',
    },
    'pelicula4': {
        'titulo': 'Zama',
        'anio': '2017',
        'duracion': '115 min',
        'direccion': 'Lucrecia Martel',
        'votos': 0,
        'sinopsis': 'Narra la historia de Don Diego de Zama, un oficial español del siglo XVII asentado en Asunción que espera su transferencia a Buenos Aires. Es un hombre que espera ser reconocido por sus méritos. Pero en los años de espera pierde todo. Decide atrapar un peligroso bandido y recuperar su nombre... Basada en la novela existencial de Antonio Di Benedetto escrita en 1956.',
        'image': 'images/zama.jpg',
    },
    'pelicula5': {
        'titulo': 'Me estás matando Susana',
        'anio': '2016',
        'duracion': '102 min',
        'direccion': 'Roberto Sneider',
        'votos': 0,
        'sinopsis': 'Eligio, un carismático y mediocre actor de 28 años, un buen día, llega a su casa y descubre que su esposa Susana se ha ido sin dar ninguna explicación. Eligio la busca por todas partes y al hablar con la gente va dándose cuenta de que entre ellos las cosas no andaban tan bien como él pensaba. Después de un par de meses, descubre que Susana se ha ido a una universidad en una pequeña ciudad del centro de los Estados Unidos; malvende su automóvil y se lanza furioso a buscarla. Desde su llegada, el impulsivo, idiosincrásico y enojado Eligio se enfrenta con la rígida y discriminadora sociedad de Iowa.',
        'image': 'images/susana.jpg',
    },
    'pelicula6': {
        'titulo': 'Urfin Dzhyus i ego derevyannye soldaty',
        'anio': '2017',
        'duracion': '82 min',
        'direccion': 'Vladimir Toropchin',
        'votos': 0,
        'sinopsis': 'El astuto y perverso Urfin decide convertirse en el gobernante de la maravillosa tierra de Oz, tomar la ciudad Esmeralda con sus soldados de madera y renombrarla como “Urfinville”. Él está casi listo para celebrar la victoria, cuando sus planes son arruinados por Dorothy, una chica normal que termina en Oz junto a su perrito Toto justo en el momento adecuado. Ella debe regresar a su casa, pero antes ayudará a sus amigos: El Espantapájaros, El Hombre de Lata y El León, para derrotar a Urfin. ',
        'image': 'images/oz.jpg',
    },
    'pelicula7': {
        'titulo': 'Le jeune Karl Marx',
        'anio': '2017',
        'duracion': '112 min',
        'direccion': 'Raoul Peck',
        'votos': 0,
        'sinopsis': 'En el París de 1844, tras exiliarse, Karl Marx conoce a Friedrich Engels, quien investigaba el nacimiento de la clase obrera británica. Engels proporcionó la última pieza del puzle a la visión del mundo del joven Marx. Juntos, entre censuras, represión policial, revueltas y conflictos políticos, lideraron el movimiento obrero durante su desarrollo hacia la era moderna.',
        'image': 'images/karlMarx.jpg',
    },
    'pelicula8': {
        'titulo': 'Girls Trip',
        'anio': '2017',
        'duracion': '122 min',
        'direccion': 'Malcolm D. Lee',
        'votos': 0,
        'sinopsis': 'Cuatro viejas amigas de la infancia viajan a Nueva Orleans para el Essence Festival, aprovechando que una de ellas, la escritora de libros de auto-ayuda Ryan Pierce (Regina Hall), va a dar una charla sobre su nuevo libro. Durante el viaje la amistad entre ellas se reavivará, pero también sus lados salvajes saldrán a la luz y habrá bailes, conflictos y romances.',
        'image': 'images/girlsTrip.jpg',
    },
    'pelicula9': {
        'titulo': 'Las heridas del viento',
        'anio': '2017',
        'duracion': '75 min',
        'direccion': 'Juan Carlos Rubio',
        'votos': 0,
        'sinopsis': 'La muerte de su padre obliga a David a hacerse cargo de su legado. Entre sus pertenencias encuentra algo inesperado: las cartas de amor de otro hombre. Desconcertado por el descubrimiento, decide visita al supuesto amante de su progenitor y descubrir la verdad.',
        'image': 'images/heridas.jpg',
    },
    'pelicula10': {
        'titulo': 'Call Me by Your Name',
        'anio': '2017',
        'duracion': '130 min',
        'direccion': 'Luca Guadagnino',
        'votos': 0,
        'sinopsis': 'Elio Perlman (Timothée Chalamet), un joven de 17 años, pasa el cálido y soleado verano de 1983 en la casa de campo de sus padres en el norte de Italia. Se pasa el tiempo holgazaneando, escuchando música, leyendo libros y nadando hasta que un día el nuevo ayudante americano de su padre llega a la gran villa. Oliver (Armie Hammer) es encantador y, como Elio, tiene raíces judías; también es joven, seguro de sí mismo y atractivo. Al principio Elio se muestra algo frío y distante hacia el joven, pero pronto ambos empiezan a salir juntos de excursión y, conforme el verano avanza, la atracción mutua de la pareja se hace más intensa.',
        'image': 'images/callMe.jpg',
    },
};

let usuarios = {
    'user1': {
        'nombre': 'Manuel',
        'email': 'manuel@gmail.com',
        'telefono': '123123123',
        'pelicula': 'pelicula1',
    },
};
